spring:
  application:
    name: esis-to-do-list

  datasource:
    url: jdbc:postgresql://localhost:5435/esis-to-do-list
    driver-class-name: org.postgresql.Driver
    username: to_do_list_user
    password: to_do_list

  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
    user: admin
    password: admin