spring:
  application:
    name: esis-to-do-list

  datasource:
    url: jdbc:postgresql://localhost:5435/esis-to-do-list_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin

  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml
    user: admin
    password: admin